name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: javac Main.java
        command: java Main
        input: |-
          1.0
          3.0
          2.0
        expected-output: x1 = -1.0 and x2 = -2.0
        comparison-method: contains
        timeout: 5
        max-score: 5
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: javac Main.java
        command: java Main
        input: |-
          0.5
          0.5
          0.125
        expected-output: x1 = -0.5 and x2 = -0.5
        comparison-method: contains
        timeout: 2
        max-score: 5
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: javac Main.java
        command: java Main
        input: |-
          1.0
          3.0
          10.0
        expected-output: x1 = NaN and x2 = NaN
        comparison-method: contains
        timeout: 2
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
      with:
        runners: test-1,test-2,test-3
